"""
a script to determine the "weights" or brightness levels of characters. for later use by the unicodeify script
i got the idea to do things this way from https://www.codeproject.com/Articles/1179876/Unicode-Art
(i did not use any of the code provided, though)
"""

import io

from PIL import Image, ImageDraw, ImageFont
from numpy import floor


# width and height of the space each monospace character takes up (i counted the pixels in a screenshot)
W, H = (10, 22)

# these characters will be shown on the screen as the script runs (for quality control)
showlist = [29, 35, 42, 48, 65, 77, 97, 9608]

font = ImageFont.truetype("consola.ttf", 18, encoding='utf-8')


# return an image of the character as it would appear on the screen
# i'm pretty sure i consulted a stackoverflow question or a tutorial for this particular function
def get_image(char):
    img = Image.new("RGB", (W, H), (0, 0, 0))
    draw = ImageDraw.Draw(img)
    offset_w, offset_h = font.getoffset(chr(char))
    w, h = draw.textsize(str(chr(char)), font=font)
    pos = ((W - w - offset_w) / 2, (H - h - offset_h) / 2)
    draw.text(pos, chr(char), "white", font=font)  # draw the character in white on black
    return img


# average out the pixels to find the weight
def get_weight(img):
    total_color = 0
    for i in range(W):
        for j in range(H):
            total_color += img.getpixel((i, j))[0]
    return int(floor(total_color/(W*H)))


# character_list.txt is generated by list_characters_script
def get_chars():
    with io.open('character_list.txt', 'r', encoding="utf-8") as f:
        chars = list(map(int, f.readlines()[0].split(" ")))
    return chars


def get_weights():
    chars = get_chars()
    weights = []

    for i in range(255):
        weights.append("")  # initialize array with empty strings

    for i in chars:
        image = get_image(i)
        weight = get_weight(image)

        weights[weight] += " " + str(i)

    return weights


def main():
    weights = get_weights()

    with open('weights.txt', 'w') as f:

        for i in range(len(weights)):
            if len(weights[i]) > 0:
                f.write(str(i) + ":")
                f.write(weights[i])
                f.write("\n")


main()
